

#ifndef STACK_MEM_CFG_H_
#define STACK_MEM_CFG_H_

#include "static_buffer.h"
#include "queued_async_framework.h"
#include "cache_management.h"


#define NETWROK_TX_ENV_NUM (6 * 2)
#define ACCESS_TX_ENV_NUM  (5 * 2)// 2->10

#define NETWORK_TX_PROCESS_BUF_QUEUE_LENGTH NETWROK_TX_ENV_NUM
#define NETWORK_TX_PDU_BUF_SIZE  (NETWROK_TX_ENV_NUM + 48)  //add friend queue size
#define ACCESS_TX_BUF_QUEUE_LENGTH ACCESS_TX_ENV_NUM   
#define ACCESS_RX_PROCESS_BUF_QUEUE_LENGTH (20 * 2)

#define NETWORK_RX_PROCESS_BUF_QUEUE_LENGTH (20 * 2)
#define AES_128_QUEUE_LENGTH 3
#define CCM_CMAC_BUF_QUEUE_LENGTH 5
#define OBFUSCATION_BUF_QUEUE_LENGTH 2

#define CALC_CONFIRMATION_QUEUE_LENGTH 1
#define CALC_SESSION_KEY_QUEUE_LENGTH 1
#define CHECK_CONFIRMATION_QUEUE_LENGTH 1
#define ENCRYPT_DATA_QUEUE_LENGTH 1
#define DEVKEY_CALC_QUEUE_LENGTH 1

#define PROVISION_REASSEMBLY_ENV_BUF_SIZE 3
#define PROVISION_TX_PDU_BUF_SIZE 3
#define CONTROL_TX_PDU_BUF_SIZE 3
#define ACCESS_TX_PDU_BUF_SIZE (10 * 2)   
#define NETWORK_ADV_TX_BUF_SIZE (33 * 2)  // 5->33
#define BEACON_ADV_TX_BUF_SIZE 5
#define PB_ADV_TX_BUF_SIZE 6
#define REASSEMBLY_ENV_BUF_SIZE (10 *2)
#define RELAY_PROTECT_BUF_SIZE 15
#define NETWORK_PDU_RX_BUF_SIZE (20 * 3)
#define UPPER_PDU_RX_BUF_SIZE 3
#define UPPER_TX_BUF_NUM 5
#define UPPER_TX_ENV_BUF_SIZE (UPPER_TX_BUF_NUM)
#define UPPER_TX_MNGT_BUF_SIZE (UPPER_TX_BUF_NUM)
#define GATT_SERVICE_ADV_TX_BUF_SIZE 6
#define NETWORK_MSG_CACHE_SIZE 20
#define ADV_MESH_MSG_CACHE_SIZE (NETWORK_PDU_RX_BUF_SIZE/2)
#define BEACON_MESH_MSG_CACHE_SIZE 5
#define PROV_CLIENT_BUF_SIZE 3
#define INCOMPELTE_RX_LIST_SIZE 10


#define QUEUE_LENGTH_PER_FRIEND 16
#define SUBSCRIPTION_LIST_SIZE_PER_FRIEND 10
#define SUPPORTED_LOW_POWER_NODE_NUMS 3

#define FRIEND_REQUEST_ATTEMPTS_MAX 6


#endif
