#ifndef MESH_KEY_REFRESH_TEST_H_
#define MESH_KEY_REFRESH_TEST_H_


typedef enum
{
    SCENE_KR_CLIENT_START_UPDATE,
    SCENE_KR_CLIENT_RECEIVE_UPDATE_ACK = 0x1,
    SCENE_KR_SERVER_UPDATE_NETKEY,
    SCENE_KR_SERVER_RECEIVE_REFRESH_FLAG,
    SCENE_KR_SERVER_RECEIVE_FLAG,
    SCENE_KR_SERVER_INVOKE_KEY = 0x5,
    SCENE_KR_CLIENT_TEST_UPDATE_NETKEY,
    SCENE_KR_CLIENT_TEST_IN_TWONODE,
    SCENE_KR_CLIENT_CLEAR_CACHE,
    SCENE_KR_OUTPUT_ENV,
    SCENE_KR_REMOVE_API= 0xa,
    SCENE_KR_REMOVE_RESET,
} mesh_kr_update_scene_cmd;


void mesh_kr_update_scene_test(uint32_t scene);


#endif

